-- SFVOF: separat schema, tabeller och grundläggande RLS för isolerad login/access.
-- Denna SQL ska INTE blandas ihop med Gäddhäng-tabeller eller policies.
-- Körs separat i Supabase SQL Editor.

create schema if not exists sfvof;

create table if not exists sfvof.members (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  name text not null,
  email text not null,
  is_admin boolean not null default false,
  is_active boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint sfvof_members_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade
);

create table if not exists sfvof.measurements (
  id bigint generated by default as identity primary key,
  registered_by_user_id uuid not null,
  registered_by_name text not null,
  fish_length_cm numeric(6,2) not null,
  length_interval_id integer,
  length_interval_label text,
  gps_lat double precision not null,
  gps_lng double precision not null,
  measured_at timestamptz not null,
  image_url text,
  comment text,
  is_approved boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint sfvof_measurements_registered_by_user_id_fkey
    foreign key (registered_by_user_id)
    references auth.users (id)
    on delete cascade,
  constraint sfvof_measurements_fish_length_positive
    check (fish_length_cm > 0),
  constraint sfvof_measurements_lat_range
    check (gps_lat between -90 and 90),
  constraint sfvof_measurements_lng_range
    check (gps_lng between -180 and 180)
);

create index if not exists sfvof_members_user_id_idx
  on sfvof.members (user_id);

create index if not exists sfvof_measurements_registered_by_user_id_idx
  on sfvof.measurements (registered_by_user_id);

create index if not exists sfvof_measurements_measured_at_idx
  on sfvof.measurements (measured_at desc);

create or replace function sfvof.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function sfvof.is_sfvof_admin(check_user_id uuid)
returns boolean
language sql
security definer
set search_path = sfvof, public
stable
as $$
  select exists (
    select 1
    from sfvof.members m
    where m.user_id = check_user_id
      and m.is_admin = true
      and m.is_active = true
  );
$$;

drop trigger if exists sfvof_members_set_updated_at on sfvof.members;
create trigger sfvof_members_set_updated_at
before update on sfvof.members
for each row
execute function sfvof.set_updated_at();

drop trigger if exists sfvof_measurements_set_updated_at on sfvof.measurements;
create trigger sfvof_measurements_set_updated_at
before update on sfvof.measurements
for each row
execute function sfvof.set_updated_at();

grant usage on schema sfvof to authenticated;
grant select on sfvof.members to authenticated;
grant select on sfvof.measurements to authenticated;
grant execute on function sfvof.is_sfvof_admin(uuid) to authenticated;

alter table sfvof.members enable row level security;
alter table sfvof.measurements enable row level security;

drop policy if exists "sfvof members select own or admin" on sfvof.members;
create policy "sfvof members select own or admin"
on sfvof.members
for select
to authenticated
using (
  auth.uid() = user_id
  or sfvof.is_sfvof_admin(auth.uid())
);

drop policy if exists "sfvof measurements select own or admin" on sfvof.measurements;
create policy "sfvof measurements select own or admin"
on sfvof.measurements
for select
to authenticated
using (
  auth.uid() = registered_by_user_id
  or sfvof.is_sfvof_admin(auth.uid())
);

-- Medvetet restriktivt i första steget:
-- inga klientskrivningar ännu. Lägg till separata insert/update/delete-policies senare,
-- när mätflödet byggs färdigt och kan testas isolerat.
